# Generated by Django 4.0.4 on 2022-05-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=400)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='Not Started', max_length=13)),
                ('ETA', models.DateField()),
            ],
        ),
    ]
